with-expecter: true
dir: "mocks"
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/0xPolygon/zkevm-ethtx-manager/ethtxmanager:
    interfaces:
      EthermanInterface:
        config:
      StorageInterface:
        config:
          dir: "{{.InterfaceDir}}"
          filename: "{{.InterfaceName | lower }}.generated.go"
          mockname: "{{.InterfaceName}}Mock"
          outpkg: "{{.PackageName}}"
          inpackage: True
