with-expecter: true
dir: "mocks"
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/0xPolygon/zkevm-ethtx-manager/types:
    interfaces:
      StorageInterface:
        config: 
      EthermanInterface:
        config:
  github.com/0xPolygon/zkevm-ethtx-manager/etherman:
      interfaces:
        EthereumClient:
          config:
  github.com/agglayer/go_signer/signer/types:
    interfaces:
      Signer:
        config: