[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[Etherman]
URL = "http://your.L1node.url"
ForkIDChunkSize = 20000
MultiGasProvider = false
	[Etherman.Etherscan]
		ApiKey = ""

[EthTxManager]
ForcedGas = 0
PrivateKeys = [
	{Path = "/pk/sequencer.keystore", Password = "testonly"},
	{Path = "/pk/aggregator.keystore", Password = "testonly"}
	]
	[EthTxManager.DB]
	User = "ethtxmanager_user"
	Password = "ethtxmanager_password"
	Name = "ethtxmanager_db"
	Host = "zkevm-ethtxmanager-db"
	Port = "5432"
	EnableLog = false	
	MaxConns = 200

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = false
