---
name: Test unit

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  test-unit:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.23.x ]
        goarch: [ "amd64" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOARCH: ${{ matrix.goarch }}

    - name: Test
      run: make test-unit
    